import {
  createHash,
  createPrivateKey,
  generateKeyPairSync,
  randomBytes,
  sign,
  X509Certificate,
  type KeyObject,
} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  bitString,
  boolean,
  explicit,
  implicitPrimitive,
  integer,
  octetString,
  oid,
  positiveInteger,
  sequence,
  set,
  time,
  toPem,
  utf8String,
} from './der.js';
import type { Logger } from '../kernel.js';

/**
 * The certificate LocalCast presents on the local network.
 *
 * Sharing over the LAN used to mean plain HTTP, which is the one place in the product where
 * bytes crossed a network unencrypted — and where anyone else on the same Wi-Fi could read a
 * film, a document or a bearer token straight off the air. This module removes that.
 *
 * It is a **self-signed** certificate, generated by the app, and no certificate authority is
 * installed on any device. That is a deliberate limit: installing a CA on a phone means a
 * configuration profile on iOS and a trust store the user cannot easily undo, which is a far
 * larger thing to ask than the one-time browser warning this costs instead.
 *
 * The trade is a net gain rather than a pure cost. A plain-HTTP origin is not a secure
 * context, so LAN mode had no service worker (no offline library) and no camera (no QR
 * scanning). An `https://` origin has both, once the certificate is accepted.
 *
 * Two properties matter more than anything else here:
 *
 *   1. **The certificate is stable.** It is written to disk and reused. A certificate that
 *      changed on every launch would mean a browser warning on every launch, and a warning
 *      people see daily is a warning they stop reading.
 *   2. **The fingerprint is published.** A phone's browser cannot check it, but the Windows
 *      client can pin it, and putting it in the QR payload means the value is stated rather
 *      than implied.
 */

export interface LanCertificate {
  keyPem: string;
  certPem: string;
  /**
   * Uppercase colon-separated hex — byte for byte what `X509Certificate.fingerprint256` and
   * `tls.TLSSocket.getPeerCertificate().fingerprint256` report, so a pinning client can
   * compare without reformatting either side.
   */
  fingerprint256: string;
  /** Every name and address in the SAN, in the order they were written. */
  hosts: string[];
  /**
   * The address to publish to devices: the machine's LAN IPv4 when it has one, otherwise its
   * hostname. Always a member of `hosts`, so the address handed out is always one the
   * certificate actually covers.
   */
  publishHost: string | null;
  validFrom: Date;
  validTo: Date;
}

/** Two years. Long enough that nobody meets the warning twice; short enough to be a leaf. */
const LIFETIME_MS = 2 * 365 * 24 * 60 * 60 * 1000;

/**
 * Regenerate this far ahead of expiry. Without the margin a machine left running across the
 * expiry moment would keep serving a dead certificate until someone restarted the app.
 */
const RENEW_BEFORE_MS = 30 * 24 * 60 * 60 * 1000;

const KEY_FILE = 'lan-key.pem';
const CERT_FILE = 'lan-cert.pem';

/** Strict 0–255 per octet: the SAN encoder writes each octet as one byte, so 300 must not pass. */
const OCTET = '(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)';
const IPV4 = new RegExp(`^${OCTET}(?:\\.${OCTET}){3}$`);
/** One DNS label per dot-separated part; `os.hostname()` can return things that are not. */
const DNS_NAME = /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*$/;

function isPrivateV4(ip: string): boolean {
  return ip.startsWith('192.168.') || ip.startsWith('10.') || /^172\.(1[6-9]|2\d|3[01])\./.test(ip);
}

/**
 * The machine's addresses on the local network, private ranges first.
 *
 * Loopback and link-local are skipped, and a private address is preferred, because a VPN
 * adapter or a container bridge can otherwise supply an address no phone in the house can
 * reach — and an address in the certificate that nobody can connect to is a certificate that
 * produces a name-mismatch error on top of the untrusted-issuer one.
 */
export function lanIpv4Addresses(interfaces = os.networkInterfaces()): string[] {
  const found: string[] = [];
  for (const addresses of Object.values(interfaces)) {
    for (const address of addresses ?? []) {
      if (address.family !== 'IPv4' || address.internal) continue;
      if (address.address.startsWith('169.254.')) continue;
      found.push(address.address);
    }
  }
  return [...found.filter(isPrivateV4), ...found.filter((ip) => !isPrivateV4(ip))];
}

/**
 * The full SAN set: loopback (so the same certificate works when the app talks to itself),
 * the machine's name, and every LAN address it currently holds.
 *
 * `<hostname>.local` is included because Windows and Bonjour both resolve it, and a name is
 * kinder to type on a phone than four numbers.
 */
export function defaultSanHosts(extra: readonly string[] = []): string[] {
  const hosts = ['localhost', '127.0.0.1'];
  const hostname = os.hostname().trim().toLowerCase();
  if (DNS_NAME.test(hostname)) {
    hosts.push(hostname);
    if (!hostname.includes('.')) hosts.push(`${hostname}.local`);
  }
  hosts.push(...lanIpv4Addresses());
  for (const host of extra) {
    const normalised = host.trim().toLowerCase();
    if (normalised.length > 0) hosts.push(normalised);
  }
  return [...new Set(hosts)].filter((host) => IPV4.test(host) || DNS_NAME.test(host));
}

/** The address devices are told to use, chosen from a SAN set. */
function publishHostFrom(hosts: readonly string[]): string | null {
  const ips = hosts.filter((host) => IPV4.test(host) && host !== '127.0.0.1');
  const preferred = ips.find(isPrivateV4) ?? ips[0];
  if (preferred !== undefined) return preferred;
  // No usable IPv4 at all — the machine is off the network, or only has IPv6. The hostname is
  // still in the certificate, so a device that can resolve it can still connect.
  return hosts.find((host) => !IPV4.test(host) && host !== 'localhost') ?? null;
}

// ─── OIDs ─────────────────────────────────────────────────────────────────────

const OID_COMMON_NAME = '2.5.4.3';
const OID_ECDSA_SHA256 = '1.2.840.10045.4.3.2';
const OID_BASIC_CONSTRAINTS = '2.5.29.19';
const OID_KEY_USAGE = '2.5.29.15';
const OID_SUBJECT_ALT_NAME = '2.5.29.17';
const OID_EXT_KEY_USAGE = '2.5.29.37';
const OID_SUBJECT_KEY_ID = '2.5.29.14';
const OID_SERVER_AUTH = '1.3.6.1.5.5.7.3.1';

function extension(id: string, critical: boolean, value: Buffer): Buffer {
  return critical
    ? sequence(oid(id), boolean(true), octetString(value))
    : sequence(oid(id), octetString(value));
}

/** `GeneralNames`: `[2] dNSName` for a name, `[7] iPAddress` for four raw address bytes. */
function subjectAltNames(hosts: readonly string[]): Buffer {
  const names = hosts.map((host) =>
    IPV4.test(host)
      ? implicitPrimitive(7, Buffer.from(host.split('.').map((part) => Number.parseInt(part, 10))))
      : implicitPrimitive(2, Buffer.from(host, 'ascii')),
  );
  return sequence(...names);
}

/**
 * The raw public point, which is what `SubjectKeyIdentifier` is a SHA-1 of. Taken from the
 * JWK export rather than by parsing the SPKI DER back apart: for P-256 the point is exactly
 * `0x04 || x || y`, and asking the runtime for the coordinates is both shorter and harder to
 * get subtly wrong than re-implementing a parser for something we just serialised.
 */
function publicKeyPoint(publicKey: KeyObject): Buffer {
  const jwk = publicKey.export({ format: 'jwk' }) as { x?: string; y?: string };
  if (jwk.x === undefined || jwk.y === undefined) throw new Error('not an EC public key');
  return Buffer.concat([
    Buffer.from([0x04]),
    Buffer.from(jwk.x, 'base64url'),
    Buffer.from(jwk.y, 'base64url'),
  ]);
}

export interface GenerateOptions {
  hosts: readonly string[];
  /** Test seam. Production reads the clock once, at generation. */
  now?: number;
  commonName?: string;
}

/**
 * Build and self-sign a P-256 certificate over `hosts`.
 *
 * P-256 rather than RSA: it is accepted everywhere a browser runs, the key generation is
 * instant (RSA-2048 can take a noticeable fraction of a second on a slow laptop, and this
 * runs during app startup), and `crypto.sign` emits the DER ECDSA signature X.509 wants with
 * no reformatting.
 */
export function generateLanCertificate(options: GenerateOptions): LanCertificate {
  const hosts = [...options.hosts];
  if (hosts.length === 0) throw new Error('a certificate needs at least one name');

  const { privateKey, publicKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });

  const notBefore = new Date((options.now ?? Date.now()) - 60_000); // clock skew on the phone
  const notAfter = new Date(notBefore.getTime() + LIFETIME_MS);
  const commonName = options.commonName ?? 'LocalCast';

  // Issuer and subject are the same Name — that is what "self-signed" means on the wire.
  const name = sequence(set(sequence(oid(OID_COMMON_NAME), utf8String(commonName))));
  const algorithm = sequence(oid(OID_ECDSA_SHA256));
  const spki = Buffer.from(publicKey.export({ type: 'spki', format: 'der' }));

  const tbs = sequence(
    explicit(0, integer(2)), // v3; anything with extensions must say so
    positiveInteger(randomBytes(16)),
    algorithm,
    name,
    sequence(time(notBefore), time(notAfter)),
    name,
    spki,
    explicit(
      3,
      sequence(
        // An end-entity certificate, explicitly: this is a server certificate and must never
        // be usable to sign another one, even on a device where somebody has trusted it.
        extension(OID_BASIC_CONSTRAINTS, true, sequence()),
        // digitalSignature only. Bit 0 set, so seven bits of the byte are padding.
        extension(OID_KEY_USAGE, true, bitString(Buffer.from([0x80]), 7)),
        extension(OID_EXT_KEY_USAGE, false, sequence(oid(OID_SERVER_AUTH))),
        extension(OID_SUBJECT_ALT_NAME, false, subjectAltNames(hosts)),
        extension(
          OID_SUBJECT_KEY_ID,
          false,
          octetString(createHash('sha1').update(publicKeyPoint(publicKey)).digest()),
        ),
      ),
    ),
  );

  const signature = sign('sha256', tbs, privateKey);
  const certDer = sequence(tbs, algorithm, bitString(signature));

  const certPem = toPem('CERTIFICATE', certDer);
  const keyPem = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();

  // Read back what we just wrote, through a parser we did not write, and check the signature
  // verifies. A DER bug here would otherwise surface as an unreadable TLS failure on a phone.
  const parsed = new X509Certificate(certPem);
  if (!parsed.verify(publicKey) || !parsed.checkPrivateKey(privateKey)) {
    throw new Error('the generated certificate did not verify against its own key');
  }

  return {
    keyPem,
    certPem,
    fingerprint256: parsed.fingerprint256,
    hosts,
    publishHost: publishHostFrom(hosts),
    validFrom: notBefore,
    validTo: notAfter,
  };
}

export interface EnsureOptions {
  /** Directory the key and certificate live in. Created if missing. */
  dir: string;
  /** Extra SAN entries on top of the auto-detected set. */
  extraHosts?: readonly string[];
  now?: number;
  log?: Logger;
}

/**
 * Load the stored certificate, or make a new one.
 *
 * Regeneration happens for exactly two reasons, and both of them are things the user would
 * otherwise experience as "it stopped working": the certificate has expired (or is about to),
 * or the machine's LAN address has changed and is no longer covered by the SAN — a DHCP lease
 * moving from `192.168.1.50` to `192.168.1.73` is enough. Anything else reuses the file,
 * because a new certificate means a new warning.
 */
export function ensureLanCertificate(options: EnsureOptions): LanCertificate {
  const now = options.now ?? Date.now();
  const hosts = defaultSanHosts(options.extraHosts ?? []);
  const keyPath = path.join(options.dir, KEY_FILE);
  const certPath = path.join(options.dir, CERT_FILE);

  const existing = loadLanCertificate(keyPath, certPath, hosts, now);
  if (existing) return existing;

  const generated = generateLanCertificate({ hosts, now });
  fs.mkdirSync(options.dir, { recursive: true });
  // 0o600 on the key. It is honoured on POSIX and ignored on Windows, where the data
  // directory is already under the user's profile — but the intent belongs in the code.
  fs.writeFileSync(keyPath, generated.keyPem, { encoding: 'utf8', mode: 0o600 });
  fs.writeFileSync(certPath, generated.certPem, 'utf8');
  options.log?.info('local-network certificate issued', {
    hosts: generated.hosts.join(', '),
    fingerprint: generated.fingerprint256,
    validTo: generated.validTo.toISOString(),
  });
  return generated;
}

/** Returns the stored pair when it is still usable for `hosts`, otherwise null. */
function loadLanCertificate(
  keyPath: string,
  certPath: string,
  hosts: readonly string[],
  now: number,
): LanCertificate | null {
  let keyPem: string;
  let certPem: string;
  try {
    keyPem = fs.readFileSync(keyPath, 'utf8');
    certPem = fs.readFileSync(certPath, 'utf8');
  } catch {
    return null;
  }

  try {
    const parsed = new X509Certificate(certPem);
    const privateKey = createPrivateKey(keyPem);
    if (!parsed.checkPrivateKey(privateKey)) return null;
    // Self-signed, so its own public key is the one that must verify it. A file that fails
    // this has been tampered with or truncated.
    if (!parsed.verify(parsed.publicKey)) return null;

    const validFrom = new Date(parsed.validFrom);
    const validTo = new Date(parsed.validTo);
    if (Number.isNaN(validTo.getTime())) return null;
    if (validFrom.getTime() > now) return null;
    if (validTo.getTime() - now < RENEW_BEFORE_MS) return null;

    // `checkHost`/`checkIP` rather than a hand-parse of the SAN string: the matching rules
    // (wildcards, case, IPv6 spelling) belong to the same code that will do the matching
    // during the handshake, not to a regex written here.
    for (const host of hosts) {
      const covered = IPV4.test(host)
        ? parsed.checkIP(host) !== undefined
        : parsed.checkHost(host) !== undefined;
      if (!covered) return null;
    }

    return {
      keyPem,
      certPem,
      fingerprint256: parsed.fingerprint256,
      hosts: sanHostsOf(parsed),
      publishHost: publishHostFrom(hosts),
      validFrom,
      validTo,
    };
  } catch {
    // A truncated or hand-edited file. Replacing it is the only useful response.
    return null;
  }
}

/** The SAN entries as plain strings, for logs and for the panel. Display only. */
function sanHostsOf(cert: X509Certificate): string[] {
  const raw = cert.subjectAltName;
  if (!raw) return [];
  return raw
    .split(',')
    .map((part) => part.trim())
    .map((part) => part.replace(/^(?:DNS|IP Address|IP|URI|email):/i, '').trim())
    .filter((part) => part.length > 0);
}
